project_id = "mfaxpkfpackofxklccyl"

[functions.arquivar-mensagens-antigas]
verify_jwt = false

[functions.consolidar-uso-diario]
verify_jwt = false

[functions.processar-followups-agendados]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.evolution-create-instance]
verify_jwt = false

[functions.evolution-connect]
verify_jwt = false

[functions.evolution-disconnect]
verify_jwt = false

[functions.evolution-connection-status]
verify_jwt = false

[functions.evolution-set-webhook]
verify_jwt = false

[functions.evolution-delete-instance]
verify_jwt = false

[functions.enviar-mensagem]
verify_jwt = false
